### ISSUE TITLE
A galore of unthemed icons

### ISSUE THREAD

**Issue by birdie-github** [Aris-t2/CustomCSSforTb#3]
Thunderbird for Linux 68.2.1.

See the attached screenshot.

My UserChrome.css modifications:

```diff
diff -u userChrome.css.default userChrome.css 
--- userChrome.css.default	2019-09-08 16:02:00.000000000 +0000
+++ userChrome.css	2019-11-01 16:33:25.006605369 +0000
@@ -71,14 +71,14 @@
 /* @import "./css/buttons/ctb_button_size_menubar.css"; /**/
 
 /* Buttons on tabs toolbar - [only use one at a time] *******************************************/
-/* @import "./css/buttons/tab_toolbar_buttons_before_tabs.css"; /**/
+   @import "./css/buttons/tab_toolbar_buttons_before_tabs.css"; /**/
 /* @import "./css/buttons/tab_toolbar_buttons_hidden.css"; /**/
 
 /* Icon settings ********************************************************************************/
 /* @import "./css/buttons/reduce_icon_size_on_hover.css"; /**/
 
 /* Icon sets - [only use one at a time] *********************************************************/
-/* @import "./css/buttons/tb_icons_tb1.css"; /**/
+   @import "./css/buttons/tb_icons_tb1.css"; /**/
 /* @import "./css/buttons/tb_icons_tb2.css"; /**/
 /* @import "./css/buttons/tb_icons_tb3.css"; /**/
 /* @import "./css/buttons/tb_icons_tb3_strata.css"; /**/
```

Also I don't understand what the asterisks are for - all those folders don't have any unread messages:
![icons](https://user-images.githubusercontent.com/4958603/68040135-87495e00-fcc5-11e9-835e-7d5aefac5980.png)

**Comment by birdie-github** [comment]
Some more:
![icons2](https://user-images.githubusercontent.com/4958603/68040327-08085a00-fcc6-11e9-8271-fb869b98d3b3.png)

**Comment by Aris-t2** [comment]
The `tb_icons_tb*` "options only swap icons previously used inside images like these. 

![tb_compose_tb3_strata](https://user-images.githubusercontent.com/6013569/68043761-532a6900-fcd6-11e9-8110-67a89d74f1db.png)

![tb_folder_tb3strata](https://user-images.githubusercontent.com/6013569/68043762-532a6900-fcd6-11e9-8c94-59d39def231d.png)

![tb_mail_tb3_strata](https://user-images.githubusercontent.com/6013569/68043764-53c2ff80-fcd6-11e9-827e-42c60912c28e.png)


Other buttons/images do not get swapped as the main goal was to change the icons of toolbar buttons at least back then. Haven't looked into it since then.

**Comment by Aris-t2** [comment]
Current preview builds removed "theming folder icons" when using custom icons for toolbar buttons.
In fact it is not recommended to change folder icons anymore since Thunderbird 78 is now official.
